### PR TITLE
Issue 273 Fix HTML generation for delete form dialog

### LINKED ISSUE #273: HTML is being shown in line in form deletion dialog
#### Software and hardware versions 
Aggregate v1.6.0-beta.0

#### Problem description
If you delete a form, you get a dialog that reads...
```Delete all data and the form definition for <b>timestamp_test</b>?<br/>Do you wish to delete all uploaded data and the form definition for this form?```

#### Expected behavior
I don't expect to see HTML inline.

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #273

#### What has been done to verify that this works as intended?
Verified that the dialog works as expected:

image

#### Why is this the best possible solution? Were any other approaches considered?
Straightforward fix.

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Do we need any specific form for testing your changes? If so, please attach one
Nope.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope.

### CODE REVIEW

**Comment by yanokwa** [comment]
@ggalmazor Can you search for instances of `new SafeHtmlBuilder().appendEscaped` that wrap HTML tags (b, br, u, i, a, etc) and make sure those are fixed too?

**Comment by kkrawczyk123** [comment]
I have noticed that when purging incomplete submissions on dialog message submission id is not bolded and it is displayed in a bracket, screenshot attached:
screenshot from 2018-07-05 15-37-50
screenshot from 2018-07-05 15-37-31

It would be good to unified them all :)

**Comment by ggalmazor** [comment]
Added a commit to normalize those dialogs too:

image
image

**Comment by kkrawczyk123** [comment]
I confirm that the result is compliant with the screenshot attached above.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

File: src/main/java/org/opendatakit/aggregate/client/popups/PurgeUpToDatePopup.java [hunk 1]
```diff
@@ -70,7 +70,7 @@ public void onValueChange(ValueChangeEvent<Date> event) {
     layout.setWidget(0, 0, new HTML(new SafeHtmlBuilder()
         .appendEscaped("Purge submissions data for:")
         .appendHtmlConstant("<br/>")
-        .appendEscaped(formSummary.getTitle() + " [" + formSummary.getId() + "]")
+        .appendHtmlConstant("<b>" + summary.getTitle() + " [" + summary.getId() + "]</b>")
```
Comment (yanokwa) [inline src/main/java/org/opendatakit/aggregate/client/popups/PurgeUpToDatePopup.java]: Why did this change from formSummary to summary?

Comment (yanokwa) [reply src/main/java/org/opendatakit/aggregate/client/popups/PurgeUpToDatePopup.java]: Never mind. Looked at the full source and it makes sense now 👍

Comment (ggalmazor) [reply src/main/java/org/opendatakit/aggregate/client/popups/PurgeUpToDatePopup.java]: I copied and pasted the line from `ConfirmPurgeUpToDatePopup.java` and it worked the same because line 48 `this.summary = formSummary;` but I've reverted that to make the change smaller.
