### PR TITLE
Issue 293 Aggregate sets a wrong size for encryption fields

### LINKED ISSUE #293: Aggregate sets a wrong size for encryption fields
#### Software and hardware versions 
Aggregate v1.16.0

#### Problem description
In #266 we fixed the parsing of the `odk:length` attribute on bindings on non-encrypted forms.

In encrypted forms, we trick Aggregate into thinking that the actual form the user has sent is the one defined in the constant `BaseFormParserForJavaRosa.ENCRYPTED_FORM_DEFINITION`, which is not parsed by the same block that was fixed in #266.

The result is that the `odk:length` attributes of the bindings of `base64EncryptedKey` and `base64EncryptedElementSignature` is ignored and set to the default string length of 255 chars.

**This will truncate the encrypted symmetric encryption keys and the submission cryptographic signature, which require at least 345 chars, __making it impossible to decrypt the submission__**

#### Steps to reproduce the problem
1. Upload to Aggregate this form
2. Send some submissions with Collect
3. Pull and export the form with Briefcase using this private key

The export will fail

#### Expected behavior
The fields should have a size of 2048 chars, as defined in the constant `BaseFormParserForJavaRosa.ENCRYPTED_FORM_DEFINITION` and exporting the form should work.

#### Other information 
N/A

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #293

This PR changes the upload form process:
- When Aggregate detects that the form is encrypted, it tricks itself into thinking that the user sent the form defined in `BaseFormParserForJavaRosa.ENCRYPTED_FORM_DEFINITION` which defined field sizes of 2048
- This PR fixes this part of the process to take into account those sizing definitions

#### What has been done to verify that this works as intended?
- Uploaded [this form](https://github.com/opendatakit/aggregate/files/2270898/encrypted-form.zip)
 and verified with PostgreSQL that the `BASE64_ENCRYPTED_KEY` and `BASE64_ENCRYPTED_ELEMENT_SIGNATURE` fields have a size of 2048 chars
- Uploaded some submissions with Collect
- Pulled the form with Briefcase
- Exported the form with Briefcase

#### Why is this the best possible solution? Were any other approaches considered?
This is the narrowest/quickest patch I came up with reusing what we're already doing with non-encrypted forms

#### Are there any risks to merging this code? If so, what are they?
I don't think so. 

#### Do we need any specific form for testing your changes? If so, please attach one
(already attached to the verification section)

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

**Comment by ggalmazor** [comment]
@opendatakit-bot label "high priority"

File: src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java [hunk 1]
```diff
@@ -546,6 +546,13 @@ protected BaseFormParserForJavaRosa(String existingXml, String existingTitle, bo
       // the
       // storage for this form.
       XFormParser exfp = parseFormDefinition(ENCRYPTED_FORM_DEFINITION);
+      // Reset bind element and string length maps since we're actually using another form definition
```
Comment (lognaturel) [inline src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java]: "we're actually using another form definition" -> "we're forcing use of a standard form definition with three fields for all encrypted forms" or something like that? Without the context we discussed on Slack I think it would have taken me a bit to look at that constant and figure out what was going on.

Comment (ggalmazor) [reply src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java]: OK, I'll expand on that

Do you think it would be helpful to add a link to #294?

Comment (lognaturel) [reply src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java]: That sounds like a good idea! Or quickly put together a page to address #294 and link to that.

**Comment by lognaturel** [comment]
Once this is merged I agree that the point release can be done off `master`.
