### PR TITLE
Revert to previous code that had the webapp's path into account

### LINKED ISSUE #419: Fix Aggregate to work as non-ROOT webapp
#### Software and hardware versions 
Aggregate v2.0.0

#### Problem description
https://github.com/opendatakit/aggregate/pull/393/commits/7f2071bd96fb2cba31662bf2e88ba0422d5b4ee4 introduced a bug that will break the login page whenever Aggregate is not deployed as ROOT webapp ( at /)

#### Steps to reproduce the problem
Deploy Aggregate as a regular webapp and try to log in.

#### Expected behavior
It should log in

#### Other information 
Urls used in links and forms can't be truly absolute. They always need to be relative to the webapp's path in Tomcat.

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #419 

#### What has been done to verify that this works as intended?
Run Aggregate in a local Tomcat both as ROOT and non-ROOT webapp, having configured a hostname and disabled the hostnames check.

In master, the login of the non-ROOT webapp won't work, and this PR solves that.

Also tested that this PR doesn't break the Cloud-Config stack by running it locally and verifying that the login still works.

#### Why is this the best possible solution? Were any other approaches considered?
This PR solves a regression bug introduced in v2.0.0. The change is to restore the original redirection code.

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Do we need any specific form for testing your changes? If so, please attach one
No.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

File: src/main/java/org/opendatakit/aggregate/servlet/ClearSessionThenLoginServlet.java [hunk 1]
```diff
@@ -63,11 +63,11 @@ protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws
     String newUrl;
     if (isAnon) {
       // anonymous user -- go to the login page...
-      newUrl = "/multimode_login.html";
```
Comment (yanokwa) [inline src/main/java/org/opendatakit/aggregate/servlet/ClearSessionThenLoginServlet.java]: Did you mean to leave out the `/`?

**Comment by kkrawczyk123** [comment]
**Tested with success!!**
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
