### PR TITLE
Issue 261 Visualize submissions on Map issue

### LINKED ISSUE #261: Visualize submissions on Map issue.
#### Software and hardware versions 
Aggregate v1.6.x, Java v1.8.x, ... 

#### Problem description
I am not able to visualize submissions on the map on tomcat instance, the map is not loading at all:
screenshot from 2018-06-21 12-43-12

I am able to visualize submissions on the map on GAE instance but with issues:
a6

#### Steps to reproduce the problem
1. Try to Visualize submissions on geolocations on the map. 

#### Expected behavior
The map should open with no issues.

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #261

This PR adds a note telling users to reload page after changing the Google Simple API key. This will reload the maps javascript library, which 

#### What has been done to verify that this works as intended?
- Used the master version to push the All Widgets form with some submissions
- Verified that the map was showing the watermarks
- Set the Google API keys
- Verified that the new note was shown
- Hit F5 to reload the page
- Verified that now the map was showing no watermarks

#### Why is this the best possible solution? Were any other approaches considered?
I considered forcing a programmatic reload of the page, but the way the form with the Google is sent prevents to do so without complicated JS code and HTML hacking.

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Do we need any specific form for testing your changes? If so, please attach one
All Widgets with some submissions will do.

[Widgets.zip](https://github.com/opendatakit/aggregate/files/2305380/Widgets.zip)

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

File: src/main/java/org/opendatakit/aggregate/servlet/ServiceAccountPrivateKeyUploadServlet.java [hunk 1]
```diff
@@ -247,6 +247,7 @@ public void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOEx
         out.write(HtmlConsts.HTML_OPEN);
         out.write(HtmlConsts.BODY_OPEN);
         out.write("<p>Successful private key information upload.</p>");
+        out.write("<p><strong>Note</strong>: If you have updated the Google Simple API Key, please, reload this page pressing the F5 key.</p>");
```
Comment (yanokwa) [inline src/main/java/org/opendatakit/aggregate/servlet/ServiceAccountPrivateKeyUploadServlet.java]: People don't know about F5 and we can't guarantee the browser so keyboard shortcuts are less helpful. 

> If you have updated the Google Simple API Key, please reload/refresh this page.

**Comment by ggalmazor** [comment]
Apparently, I had branched off of the wrong base branch. Now it should be OK.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on tomcat and GAE.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
